name: Build

env:
  SOLUTION_NAME: ShareLinkSampleXamAndroid
  ANDROID_PROJECT_NAME: ShareLinkSampleXamAndroid.Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Setup Xamarin and Mono versions
    runs-on: macos-latest
    steps:
    - name: setup-xamarin
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        xamarin-android-version: '10.1.3.7'